version: '3.8'
networks:
  zugnet:
    ipam:
      config:
        - subnet: 172.20.0.0/24
services:
  db:
    image: postgres:14-alpine
    container_name: peon.db
    environment:
      - POSTGRES_USER=gromhellscream
      - POSTGRES_PASSWORD=Zu88Zu88
    volumes:
      - $PWD/peon/db/data:/var/lib/postgresql/data
      - /var/log/peon:/var/log/peon
    networks:
      zugnet:
        ipv4_address: 172.20.0.2
    restart: always
  webapp:
    container_name: peon.ui
    image: umlatt/peon.ui:0.1.3-dev
    depends_on:
      - db
    ports:
      - '80:80'
    volumes:
      - /var/log/peon:/var/log/peon
    networks:
      zugnet:
        ipv4_address: 172.20.0.3
    restart: unless-stopped
  orchestrator:
    container_name: peon.orc
    image: umlatt/peon.orc:0.1.4-dev
    depends_on:
      - db
    ports:
      - '443:443'
    volumes:
      - /var/log/peon:/var/log/peon
      - $PWD/servers:/servers
    networks:
      zugnet:
        ipv4_address: 172.20.0.4
    restart: unless-stopped